version: '3'
services:
  mongo:
    image: tutum/mongodb
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - AUTH=no
    volumes:
      - /home/fortes/arquivos:/data/db
  ftp:
    image: bogem/ftp
    container_name: ftp
    ports:
      - "47400-47470:47400-47470"
    restart: always
    environment:
      - FTP_USER=thiago
      - FTP_PASS=thiago
      - PASV_ADDRESS=10.0.75.1
    volumes:
      - /home/ftp